sortStrings, pick, omit functions implemented
js-tasks-ru/js-20221021_antogonistick pull request #2
Opened 2022-11-02 12:32 UTC by Antogonistick

2022-11-02 12:33 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-11-03 13:40 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return sortedArr.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-11-03 13:40 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    for (const key of fields) {
обратите внимание на метод `includes`

2022-11-03 13:40 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-11-09 12:52 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-11-11 16:24 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  const compare = (a, b) => {
👍 good

2022-11-11 16:24 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const arrPath = path.split('.');
👍 good

2022-11-11 16:24 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    return undefined;
просто `return`

2022-11-11 16:24 UTC, dosandk approved these changes
good 👍

2022-11-11 16:25 UTC, merged